### ISSUE TITLE
in python3.x execute db migrate will ValueError: invalid interpolation syntax in 'xxxxx'

### ISSUE THREAD

**Issue by sprouting** [miguelgrinberg/Flask-Migrate#122]
```
(venv) zhaoyb@zhaoyb-pc:~/PycharmProjects/myblog$ python myblog.py db migrate
/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Traceback (most recent call last):
  File "myblog.py", line 64, in <module>
    manager.run()
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 173, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    modul(venv) zhaoyb@zhaoyb-pc:~/PycharmProjects/myblog$ python myblog.py db migrate
/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Traceback (most recent call last):
  File "myblog.py", line 64, in <module>
    manager.run()
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 173, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 22, in <module>
    current_app.config.get('SQLALCHEMY_DATABASE_URI'))
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/config.py", line 218, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/config.py", line 245, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/lib/python3.5/configparser.py", line 1190, in set
    super().set(section, option, value)
  File "/usr/lib/python3.5/configparser.py", line 891, in set
    value)
  File "/usr/lib/python3.5/configparser.py", line 401, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'mysql://root:ppnn13%dkstFeb.1st@localhost/myblog' at position 19
(venv) zhaoyb@zhaoyb-pc:~/PycharmProjects/myblog$ ^C
(venv) zhaoyb@zhaoyb-pc:~/PycharmProjects/myblog$ 
e = load_module_py(module_id, path)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 22, in <module>
    current_app.config.get('SQLALCHEMY_DATABASE_URI'))
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/config.py", line 218, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/home/zhaoyb/PycharmProjects/myblog/venv/lib/python3.5/site-packages/alembic/config.py", line 245, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/lib/python3.5/configparser.py", line 1190, in set
    super().set(section, option, value)
  File "/usr/lib/python3.5/configparser.py", line 891, in set
    value)
  File "/usr/lib/python3.5/configparser.py", line 401, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'mysql://root:ppnn13%dkstFeb.1st@localhost/myblog' at position 19
(venv) zhaoyb@zhaoyb-pc:~/PycharmProjects/myblog$ 
```

**Comment by miguelgrinberg** [comment]
Looks like you need to escape the `%` in your password. Also, not a great idea to write down your db password here, please make sure you change it.

**Comment by sprouting** [comment]
oh ，thanks for your reply！it's so helpful!
