### ISSUE TITLE
Access denied with migrate

### ISSUE THREAD

**Issue by deveshaggrawal19** [miguelgrinberg/Flask-Migrate#142]
**I'm trying to migrate but there is a slight problem with it. Here is the traceback**

Traceback (most recent call last):
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 688, in __init__
    self.connect()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 906, in connect
    self._request_authentication()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 1114, in _request_authentication
    auth_packet = self._read_packet()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 981, in _read_packet
    packet.check_error()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    manager.run()
  File "/srv/www/env/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/srv/www/env/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/srv/www/env/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/srv/www/env/lib/python3.4/site-packages/flask_migrate/__init__.py", line 177, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/srv/www/env/lib/python3.4/site-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/srv/www/env/lib/python3.4/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/srv/www/env/lib/python3.4/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/srv/www/env/lib/python3.4/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 72, in run_migrations_online
    connection = engine.connect()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 2018, in connect
    return self._connection_cls(self, **kwargs)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
    self.pool.unique_connection, _connection)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/srv/www/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 688, in __init__
    self.connect()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 906, in connect
    self._request_authentication()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 1114, in _request_authentication
    auth_packet = self._read_packet()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 981, in _read_packet
    packet.check_error()
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/srv/www/env/lib/python3.4/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

**But the main thing is that when I'm running the following script it runs just fine.**

from app import app
from app import db
db.app = app
for i in db.session.execute('show tables'):
        print(i)
 
**The app is the same with the same config file. Can not understand what is triggering this error in flask_migrate**

**Comment by deveshaggrawal19** [comment]
That is if the access is denied how come the script runs fine, and if the script is running fine, what is triggering the error

**Comment by miguelgrinberg** [comment]
I can't really tell you what's wrong. This has nothing to do with this extension or Alembic. For whatever reason, the credentials that are given to mysql aren't correct, so this is likely a bug in your application. Are you sure the database credentials are the same between your normal and migration usages?

Also, as a side note, it is not a good idea to use your root account. If your account ever gets leaked, then the attacker will have full access to your database. Better to create a user with only access to the one database.

**Comment by deveshaggrawal19** [comment]
I will change the root user later, first I have to make the necessary changes to make it work. The script that I wrote in the previous comment is using the same app and same DB config, but it's working fine. So I thought it must be the migration setup which is not working.

**Comment by deveshaggrawal19** [comment]
Sorry, got the bug the Manage.py file was not loading the environment variables, I fixed it. Thanks for the advice.

**Comment by nk9** [comment]
I got this same error, and in my case the issue was that I had "localhost" as the host, instead of "127.0.0.1". I am accessing the database through an SSH tunnel, and apparently MySQL doesn't consider these two hosts synonymous.
