### ISSUE TITLE
Discrepancy Between Local and Docker Environment `Migrate` Reference Name

### ISSUE THREAD

**Issue by eiathom** [miguelgrinberg/Flask-Migrate#217]
Migrate reference:

`MIGRATE = Migrate()`

Then when intialising the app and db objects:

`MIGRATE.init_app(app, FLASK_DB, os.path.join(BASE_PATH, 'migration'))`

And, `env` migration script (snippet):

```
    with engine.connect() as connection:
        context.configure(connection=connection,
                          target_metadata=target_metadata,
                          process_revision_directives=process_revision_directives,
                          **current_app.extensions['MIGRATE'].configure_args)
```

__LOGS:__
Running `flask db upgrade` locally :
```
2018-07-30 11:31:48,439 INFO app CURRENT_APP_EXTENSIONS: {'MIGRATE': <flask_migrate._MigrateConfig object at 0x7fb55a7965f8>, 'sqlalchemy': <flask_sqlalchemy._SQLAlchemyState object at 0x7fb55a79b2b0>, 'restplus': {'apidoc_registered': True}}
```

Running `flask db upgrade` containerized :
```
2018-07-30T10:29:43.555201515Z 2018-07-30 10:29:43,554 INFO app CURRENT_APP_EXTENSIONS: {'migrate': <flask_migrate._MigrateConfig object at 0x7fb0f77ec6a0>, 'sqlalchemy': <flask_sqlalchemy._SQLAlchemyState object at 0x7fb0f77f3358>, 'restplus': {'apidoc_registered': True}}
```

Why is this?

This is throwing an error while attempting perform `flask db upgrade` in a Docker image build:
```
Traceback (most recent call last):
  File "/lfs/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/lfs/venv/lib/python3.6/site-packages/flask/cli.py", line 891, in main
    cli.main(args=args, prog_name=name)
  File "/lfs/venv/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/lfs/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/lfs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lfs/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lfs/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lfs/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/lfs/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/lfs/venv/lib/python3.6/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/lfs/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/lfs/venv/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/lfs/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/lfs/venv/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/lfs/venv/lib/python3.6/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/lfs/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/lfs/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lfs/app/database/migration/env.py", line 105, in <module>
    run_migrations_online()
  File "/lfs/app/database/migration/env.py", line 96, in run_migrations_online
    **current_app.extensions['MIGRATE'].configure_args)
KeyError: 'MIGRATE'
```
__NOTE:__
The app is properly created, it is just the case issue that causes the issue.
We have renamed the reference to lowercase, `migrate` to side-step this issue but; the question remains as to why this occurs?
We only see this issue in the Docker environment.

**Comment by miguelgrinberg** [comment]
Where did you get `current_app.extensions['MIGRATE']` from? That seems like something that you added or changed, leave that code the way it was originally and I think you will be fine.

**Comment by eiathom** [comment]
That line comes from the fact, `'MIGRATE': <flask_migrate._MigrateConfig object at 0x7fb55a7965f8>` is the `flask-migrate` extension of the `current_app` and so, I am updating the `alembic` context (environment) configuration to use the defined `flask-migrate` `MIGRATE` module options, defined in the `init` function in our application code (see: `MIGRATE.init_app(app, FLASK_DB, os.path.join(BASE_PATH, 'migration'))`).

I would rather not remove the line without knowing why the extension is registered as `MIGRATE` locally but, `migrate` when in a Docker environment.

**Comment by miguelgrinberg** [comment]
I don't understand what you are saying. You have chosen to use `MIGRATE` variable, that has nothing to do with how the extension registers itself with Flask. As I said above, leave the env.py file as generated by the extension and you will be fine.

**Comment by eiathom** [comment]
I will close this issue, and an answer elsewhere.
