### ISSUE TITLE
flask db migrate Fails: Raise TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by HarshadKavathiya** [miguelgrinberg/Flask-Migrate#248]
I am using Python 2.7.15 and MySQL 8.0.13 on Mac OS X 10.14.2 and using the Following package:

Flask==1.0.2

Flask-Migrate==2.3.1,

PyMySQL==0.9.3,

Flask-SQLAlchemy==2.3.2,

SQLAlchemy==1.2.16,

alembic==1.0.7

When I run "**flask db init**", "**flask db migrate**" & "**flask db upgrade**" on the empty/clean database, it runs without any issue and create table according to model file.

**Please note that i am facing this issue second time and onward.**
After that whenever I try "**flask db migrate**" command I am getting an error as follows:

```
(venv) MACSYSTEM-2:flask_project account$ flask db migrate
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.env] descriptor 'lower' requires a 'str' object but received a 'unicode'
Traceback (most recent call last):
  File "/Users/account/PycharmProjects/flask_project/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/cli.py", line 90, in migrate
    rev_id, x_arg)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/command.py", line 197, in revision
    script_directory.run_env()
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/compat.py", line 216, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 90, in <module>
    run_migrations_online()
  File "migrations/env.py", line 83, in run_migrations_online
    raise exception
TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

```

Please guide me how I can solve this issue.

**Comment by MrAMS** [comment]
You can refer to this [question](https://stackoverflow.com/questions/53863836/typeerror-flask-script-commands-command-object-at-0x106bfd6d0-descriptor-lo), it says that you should use the MySQL **5.7** instead of **8.0**

**Comment by HarshadKavathiya** [comment]
I am facing this issue with Python 2 only, when I used python 3.6.5 and used the same code & requirements.txt, I am not getting said error. Seems like it is related to python 2 bug.

@MrAMS "Using MySQL 5.7 instead of 8.0" is not a feasible solution. It seems like a bug. So better we need to find fix not workaround.

**Comment by miguelgrinberg** [comment]
This is not something that this package is doing, Alembic is the one generating this exception.

**Comment by HarshadKavathiya** [comment]
Please refer to these. https://github.com/sqlalchemy/sqlalchemy/issues/4492

It is a bug related to SQLAlchemy. I hope it will be fixed soon.
