### ISSUE TITLE
Flask- Cannot import db and migrate

### ISSUE THREAD

**Issue by tejeshatr** [miguelgrinberg/Flask-Migrate#269]
My __init__.py is
`from flask import Flask`
`from config import Config`
`from flask_sqlalchemy import SQLAlchemy`
`from flask_migrate import Migrate`

`app = Flask(__name__)`
`app.config.from_object(Config)`
`db = SQLAlchemy(app)`
`migrate = Migrate(app, db)`

`from app import routes, models`

When I run 
`from app import db`
I get an ImportError
Same with migrate
Only 'app' (the Flask object) is getting imported. Others aren't.
I can't initialize the migration database because of this. Every time I run
`$flask db init`
I get a KeyError on 'migrate'

**Comment by miguelgrinberg** [comment]
Can you copy a complete error, including the stack trace?

**Comment by tejeshatr** [comment]
`>>> from app import db`
This results in

` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'db' from 'app' (/home/tjedi/Desktop/microblog/app/__init__.py)
`

and for 
`$flask db init`

I get the following error

`
Traceback (most recent call last):
  File "/home/tjedi/Desktop/microblog/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/flask/cli.py", line 419, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/flask_migrate/cli.py", line 31, in init
    _init(directory, multidb)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/home/tjedi/Desktop/microblog/venv/lib/python3.7/site-packages/flask_migrate/__init__.py", line 125, in init
    directory = current_app.extensions['migrate'].directory
KeyError: 'migrate'
`

**Comment by miguelgrinberg** [comment]
What is your current directory when you run these commands? You should be in `/home/tjedi/Desktop/microblog`.

Also, where is config.py located, and what are its contents?

**Comment by alirezaimi** [comment]
I have same issue with flask factory pattern and blueprint, but this is my error : 
```
Usage: flask db [OPTIONS] COMMAND [ARGS]...
Try "flask db --help" for help.

Error: No such command "init".

```

**Comment by tejeshatr** [comment]
`/home/tjedi/Desktop/microblog` was my current working directory when I executed those commands.

config.py is in the 'app' directory at `/home/tjedi/Desktop/microblog/app/config.py`

**Comment by miguelgrinberg** [comment]
@tejeshatr Thanks. There is an inconsistency in what you are telling me that we need to settle. If you are in the microblog directory and config.py is inside app, then how come the line `from config import Config` does not give you an import error?

If what you are describing is true, then to import the `Config` class you would need to do this:

    from app.config import Config

Can you explain this discrepancy? I believe this is indirectly related to your problem.

**Comment by tejeshatr** [comment]
Sorry, my bad. The config.py file is at `/home/tjedi/Desktop/microblog` not in the `app` folder

**Comment by miguelgrinberg** [comment]
@tejeshatr there's probably something else that you are not reporting correctly then. Can I see a complete copy of your `/home/tjedi/Desktop/microblog/app/__init__.py` file please? The copy that you pasted above seems edited, since you added quotes to every line. I'd like to see the raw and complete version of this file.

**Comment by tejeshatr** [comment]
Terribly sorry. Turns out I did not edit the __init__.py file in `microblog` but rather in another flask project that I've been doing on my own. It was so silly of me. Apologies for the inconvenience.

**Comment by miguelgrinberg** [comment]
No problem, glad that you are back on track.

**Comment by tobiolusa** [comment]
Thanks,  bit helpful.

**Comment by hima890** [comment]
@miguelgrinberg 
Hi .
I have problem withe flask-sqlalchemy and blueprint,  I usually create database by import the model file in python terminal and do db.create_all()
But with the blueprint and all that import it's really hard and I am getting the model not fond errors. 
Please help! 
Here is some screenshots 
![Screenshot - 25_06_2020 , 12_18_36 PM](https://user-images.githubusercontent.com/48498413/85720804-0ece5c00-b6f1-11ea-8f99-3f921861a8cf.png)
![w1](https://user-images.githubusercontent.com/48498413/85720818-1261e300-b6f1-11ea-8e53-9e661a92b6fb.png)
![Screenshot - 25_06_2020 , 12_19_31 PM](https://user-images.githubusercontent.com/48498413/85720835-17269700-b6f1-11ea-9e88-86b761aafa6a.png)

**Comment by miguelgrinberg** [comment]
@hima890 You haven't shown the error
