### ISSUE TITLE
Help with deciphering error message

### ISSUE THREAD

**Issue by androgeninc** [miguelgrinberg/Flask-Migrate#294]
Hi,

I am having trouble deciphering the error message i'm getting after trying to upgrade my local sqlite db after having added the Oauth table in my models.py, trying to implement Flask-Dance. 

No error message from migration, but when trying to upgrade it gives the below error, and i have noe idea where to look for fixes. Anyone, help?

----MIGRATE----

```
(venv) C:\Projects\WebsiteProjects\Flask\Project>flask db migrate
-m "added oauth table"
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'flask_dance_o
auth'
Generating C:\Projects\WebsiteProjects\Flask\Project\migrations\ve
rsions\fe5fdb591c36_added_oauth_table.py ... done
```

----UPGRADE----
```
(venv) C:\Projects\WebsiteProjects\Flask\Project>flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade d87c4a807aca -> fe5fdb
591c36, added oauth table
Traceback (most recent call last):
  File "C:\Users\josty\AppData\Local\Programs\Python\Python37\lib\runpy.
py", line 193, in _run_module_as_main  "__main__", mod_spec)
  File "C:\Users\josty\AppData\Local\Programs\Python\Python37\lib\runpy.
py", line 85, in _run_code  exec(code, run_globals)
  File "C:\Projects\WebsiteProjects\Flask\Project\venv\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\flask\cli.py", line 894, in main cli.main(args=args, prog_name=name)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\flask\cli.py", line 557, in main return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\click\core.py", line 717, in main   rv = self.invoke(ctx)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\click\core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\click\core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\click\core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\click\core.py", line 555, in invoke  return callback(*args, **kwargs)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\click\decorators.py", line 17, in new_func  return f(get_current_context(), *args, **kwargs)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\flask\cli.py", line 412, in decorator  return __ctx.invoke(f, *args, **kwargs)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\click\core.py", line 555, in invoke  return callback(*args, **kwargs)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\flask_migrate\cli.py", line 134, in upgrade_upgrade(directory, revision, sql, tag, x_arg)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\flask_migrate\__init__.py", line 95, in wrapped f(*args, **kwargs)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\flask_migrate\__init__.py", line 280, in upgrade command.upgrade(config, revision, sql=sql, tag=tag)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\alembic\command.py", line 276, in upgrade    script.run_env()
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\alembic\script\base.py", line 475, in run_env  util.load_python_file(self.dir, "env.py")
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\alembic\util\pyfiles.py", line 90, in load_python_file module = load_module_py(module_id, path)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-pa
ckages\alembic\util\compat.py", line 156, in load_module_py     spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 95, in <module>    run_migrations_online()
  File "migrations\env.py", line 89, in run_migrations_online    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-packages\alembic\runtime\environment.py", line 839, in run_migrations
```
-----MISSING STACKTRACE-------
```
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-packages\alembic\runtime\environment.py", line 839, in run_migrations   self.get_context().run_migrations(**kw)
  File "c:\projects\websiteprojects\flask\Project\venv\lib\site-packages\alembic\runtime\migration.py", line 361, in run_migrations step.migration_fn(**kw)
  File "C:\Projects\WebsiteProjects\Flask\Project\migrations\versions\fe5fdb591c36_added_oauth_table.py", line 25, in upgrade sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=False),
NameError: name 'sqlalchemy_utils' is not defined
```

**Comment by miguelgrinberg** [comment]
Your stack trace appears to be incomplete. Check and make sure you haven't left any lines out.

**Comment by androgeninc** [comment]
You are right. That made it easier to identify the problem. I added the missing part in my initial post. It seems to be a problem with a missing import of sqlalchemy_utils.types.json.JSONType().

From my migration file, it seems Flask-dance is adding it's own Oauth table, while the only change to my models.py a much simpler Oautj table. Any idea where i should import the JSONType? in my models.py file or can i do it in the migrations file?

----------My added Oauth table in models.py-------------

``
class OAuth(OAuthConsumerMixin, db.Model):
    provider_user_id = db.Column(db.String(256), unique=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    user = db.relationship(User)`
``

----------What turns up in my migrations file-------------


```
"""added oauth table

Revision ID: 4be15ce28d0a
Revises: d87c4a807aca
Create Date: 2019-09-28 23:56:53.083857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be15ce28d0a'
down_revision = 'd87c4a807aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_oauth')
    # ### end Alembic commands ###

````

**Comment by androgeninc** [comment]
Update: added the import in my migration file, and the db upgrade went through without errors. I'm still curious if this is the right way to do it though, and if it will cause problems when i push it so my production POSTgresql database on Heroku?

**Comment by androgeninc** [comment]
Another update. Seems to work fine in production. Case closed.
