### ISSUE TITLE
build is failing for pypy3

### ISSUE THREAD

**Issue by jugmac00** [miguelgrinberg/Flask-Migrate#299]
https://travis-ci.org/miguelgrinberg/Flask-Migrate/builds/597153845

**Comment by miguelgrinberg** [comment]
Yes, I'm aware of that. Haven't had time to investigate what changed.

**Comment by wgwz** [comment]
I saw this over here after opening up an MR: https://travis-ci.org/miguelgrinberg/Flask-Migrate/jobs/620924371

After investigating this a bit I was able to reproduce the issue locally.

Here was how I set up:

```
$ pypy3 -m venv venv
$ . venv/bin/activate
$ pip install -e .
$ python setup.py test
```
Here was my output from the last command above:
```
/home/kyle/code/Flask-Migrate/venv/site-packages/setuptools/dist.py:470: UserWarning: Normalizing '2.5.3dev
' to '2.5.3.dev0'
  normalized_version,
running test
Searching for Flask-Script>=0.6
Best match: Flask-Script 2.0.6
Processing Flask_Script-2.0.6-py3.6.egg

Using /home/kyle/code/Flask-Migrate/.eggs/Flask_Script-2.0.6-py3.6.egg
running egg_info
writing Flask_Migrate.egg-info/PKG-INFO
writing dependency_links to Flask_Migrate.egg-info/dependency_links.txt
writing entry points to Flask_Migrate.egg-info/entry_points.txt
writing requirements to Flask_Migrate.egg-info/requires.txt
writing top-level names to Flask_Migrate.egg-info/top_level.txt
reading manifest file 'Flask_Migrate.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Flask_Migrate.egg-info/SOURCES.txt'
running build_ext
test_alembic_version (tests.test_migrate.TestMigrate) ... ok
test_compare_type (tests.test_migrate.TestMigrate) ... 
$ /home/kyle/code/Flask-Migrate/venv/bin/python app_compare_type1.py db init
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations ...  done
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations/versions ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/env.py ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/script.py.mako ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/README ...  done
  Please edit configuration/connection/logging settings in '/home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini' before proceeding.



$ /home/kyle/code/Flask-Migrate/venv/bin/python app_compare_type1.py db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/versions/856c43f24d11_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'


$ /home/kyle/code/Flask-Migrate/venv/bin/python app_compare_type1.py db upgrade

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 856c43f24d11, empty message


$ /home/kyle/code/Flask-Migrate/venv/bin/python app_compare_type2.py db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/versions/0c0b0f003fa2_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected type change from VARCHAR(length=128) to String(length=10) on 'user.name'

ok
test_custom_directory (tests.test_migrate.TestMigrate) ... 
$ /home/kyle/code/Flask-Migrate/venv/bin/python app_custom_directory.py db init
  Creating directory /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations ...  done
  Creating directory /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/versions ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/env.py ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/alembic.ini ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/script.py.mako ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/README ...  done
  Please edit configuration/connection/logging settings in '/home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/alembic.ini' before proceeding.



$ /home/kyle/code/Flask-Migrate/venv/bin/python app_custom_directory.py db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/versions/0eaca2c54244_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'


$ /home/kyle/code/Flask-Migrate/venv/bin/python app_custom_directory.py db upgrade

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 0eaca2c54244, empty message

ok
test_migrate_upgrade (tests.test_migrate.TestMigrate) ... 
$ /home/kyle/code/Flask-Migrate/venv/bin/python app.py db init
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations ...  done
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations/versions ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/env.py ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/script.py.mako ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/README ...  done
  Please edit configuration/connection/logging settings in '/home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini' before proceeding.



$ /home/kyle/code/Flask-Migrate/venv/bin/python app.py db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/versions/e3ae237b6582_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'


$ /home/kyle/code/Flask-Migrate/venv/bin/python app.py db upgrade

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e3ae237b6582, empty message

ok
test_alembic_version (tests.test_migrate_flaskcli.TestMigrate) ... ok
test_compare_type (tests.test_migrate_flaskcli.TestMigrate) ... 
$ flask db init
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations ...  done
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations/versions ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/env.py ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/script.py.mako ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/README ...  done
  Please edit configuration/connection/logging settings in '/home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini' before proceeding.



$ flask db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/versions/280828af699b_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'


$ flask db upgrade

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 280828af699b, empty message


$ flask db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/versions/af8d7e5bdb45_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected type change from VARCHAR(length=128) to String(length=10) on 'user.name'

ok
test_custom_directory (tests.test_migrate_flaskcli.TestMigrate) ... 
$ flask db init
  Creating directory /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations ...  done
  Creating directory /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/versions ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/env.py ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/alembic.ini ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/script.py.mako ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/README ...  done
  Please edit configuration/connection/logging settings in '/home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/alembic.ini' before proceeding.



$ flask db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/temp_folder/temp_migrations/versions/adf550699d15_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'


$ flask db upgrade

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> adf550699d15, empty message

/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py:1895: SAWarning: Identity map already had an identity for (<class 'tests.app_custom_directory.User'>, (1,), None), replacing it with newly flushed object.   Are there load operations occurring inside of an event handler within the flush?
  "within the flush?" % (instance_key,)
ok
test_migrate_upgrade (tests.test_migrate_flaskcli.TestMigrate) ... 
$ flask db init
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations ...  done
  Creating directory /home/kyle/code/Flask-Migrate/tests/migrations/versions ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/env.py ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/script.py.mako ...  done
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/README ...  done
  Please edit configuration/connection/logging settings in '/home/kyle/code/Flask-Migrate/tests/migrations/alembic.ini' before proceeding.



$ flask db migrate
  Generating /home/kyle/code/Flask-Migrate/tests/migrations/versions/5fbc35293fd6_.py ...  done

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'user'


$ flask db upgrade

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5fbc35293fd6, empty message

ERROR
test_multidb_migrate_upgrade (tests.test_multidb_migrate.TestMigrate) ... ok
test_multidb_migrate_upgrade (tests.test_multidb_migrate_flaskcli.TestMigrate) ... /home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py:1895: SAWarning: Identity map already had an identity for (<class 'tests.app_multidb.User'>, (1,), None), replacing it with newly flushed object.   Are there load operations occurring inside of an event handler within the flush?
  "within the flush?" % (instance_key,)
/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py:1895: SAWarning: Identity map already had an identity for (<class 'tests.app_multidb.Group'>, (1,), None), replacing it with newly flushed object.   Are there load operations occurring inside of an event handler within the flush?
  "within the flush?" % (instance_key,)
ok

======================================================================
ERROR: test_migrate_upgrade (tests.test_migrate_flaskcli.TestMigrate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyle/code/Flask-Migrate/tests/test_migrate_flaskcli.py", line 66, in test_migrate_upgrade
    db.session.commit()
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py", line 2574, in _flush
    flush_context.finalize_flush_changes()
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/unitofwork.py", line 443, in finalize_flush_changes
    self.session._register_persistent(other)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/session.py", line 1888, in _register_persistent
    and mapper._identity_key_from_state(old) == instance_key
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/mapper.py", line 2728, in _identity_key_from_state
    for prop in self._identity_key_props
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/mapper.py", line 2728, in <listcomp>
    for prop in self._identity_key_props
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
    value = state._load_expired(state, passive)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/opt/pypy3/lib_pypy/_functools.py", line 80, in __call__
    return self._func(*(self._args + fargs), **fkeywords)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/loading.py", line 981, in load_scalar_attributes
    only_load_props=attribute_names,
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/loading.py", line 204, in load_on_ident
    identity_token=identity_token,
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/loading.py", line 284, in load_on_pk_identity
    return q.one()
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    util.raise_from_cause(err)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/kyle/code/Flask-Migrate/venv/site-packages/sqlalchemy/orm/loading.py", line 501, in _instance
    dict_ = instance_dict(instance)
AttributeError: 'NoneType' object has no attribute '__dict__'

----------------------------------------------------------------------
Ran 10 tests in 46.182s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=10 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=10 errors=1 failures=0>
```
