### ISSUE TITLE
upgrade hangs forever with multiple database binds, probably deadlocked

### ISSUE THREAD

**Issue by alanhamlett** [miguelgrinberg/Flask-Migrate#312]
Running `flask db upgrade` hangs forever, until I kill the process or stop the postgres server. I have 3 database binds including default. It's getting stuck when updating the version in `alembic_version` table. The migration change isn't related, even running an empty `pass` migration still hangs.

Probably, the first `default` database transaction wasn't closed before starting the second `heartbeats` migration, causing a deadlock.

Full traceback:

```
$ flask db upgrade
INFO  [alembic.env] Migrating database <default>
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5c45f1292ef8 -> 52915d0437db, create integration tables
INFO  [alembic.env] Migrating database heartbeats
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5c45f1292ef8 -> 52915d0437db, create integration tables
Traceback (most recent call last):
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
CONTEXT:  while updating tuple (0,1) in relation "alembic_version"
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "migrations/env.py", line 215, in run_migrations_online
    context.run_migrations(engine_name=name)
  File "<string>", line 8, in run_migrations
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 525, in run_migrations
    head_maintainer.update_to_step(step)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 751, in update_to_step
    self._update_version(from_, to_)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 697, in _update_version
    == literal_column("'%s'" % from_)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
CONTEXT:  while updating tuple (0,1) in relation "alembic_version"
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: UPDATE alembic_version SET version_num='52915d0437db' WHERE alembic_version.version_num = '5c45f1292ef8']
(Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 733, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 531, in do_rollback
    dbapi_connection.rollback()
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alanhamlett/git/app/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "migrations/env.py", line 235, in <module>
    run_migrations_online()
  File "migrations/env.py", line 225, in run_migrations_online
    rec['transaction'].rollback()
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1716, in rollback
    self._do_rollback()
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1754, in _do_rollback
    self.connection._rollback_impl()
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 735, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 733, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/alanhamlett/git/app/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 531, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: http://sqlalche.me/e/e3q8)
```

I can generate migrations and do things like `flask db stamp head` but can't upgrade:
```
$ flask db stamp head
INFO  [alembic.env] Migrating database <default>
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.env] Migrating database heartbeats
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.env] Migrating database integrations
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
$ flask db upgrade
INFO  [alembic.env] Migrating database <default>
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5c45f1292ef8 -> 52915d0437db, create integration tables
INFO  [alembic.env] Migrating database heartbeats
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5c45f1292ef8 -> 52915d0437db, create integration tables
```

**Comment by alanhamlett** [comment]
Fixed by running each db bind's migration in separate transaction using modified `env.py`:

```python
def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    # this callback is used to prevent an auto-migration from being generated
    # when there are no changes to the schema
    # reference: http://alembic.zzzcomputing.com/en/latest/cookbook.html
    def process_revision_directives(context, revision, directives):
        if getattr(config.cmd_opts, 'autogenerate', False):
            script = directives[0]
            if len(script.upgrade_ops_list) >= len(bind_names) + 1:
                empty = True
                for upgrade_ops in script.upgrade_ops_list:
                    if not upgrade_ops.is_empty():
                        empty = False
                if empty:
                    directives[:] = []
                    logger.info('No changes in schema detected.')

    # for the direct-to-DB use case, start a transaction on all
    # engines, then run all migrations, then commit all transactions.
    engines = {
        '': {
            'engine': engine_from_config(
                config.get_section(config.config_ini_section),
                prefix='sqlalchemy.',
                poolclass=pool.NullPool,
            )
        }
    }
    for name in bind_names:
        engines[name] = rec = {}
        rec['engine'] = engine_from_config(
            context.config.get_section(name),
            prefix='sqlalchemy.',
            poolclass=pool.NullPool)

    for name, rec in engines.items():
        engine = rec['engine']
        rec['connection'] = conn = engine.connect()

        if USE_TWOPHASE:
            rec['transaction'] = conn.begin_twophase()
        else:
            rec['transaction'] = conn.begin()

        try:
            logger.info("Migrating database %s" % (name or '<default>'))
            context.configure(
                connection=rec['connection'],
                upgrade_token="%s_upgrades" % name,
                downgrade_token="%s_downgrades" % name,
                target_metadata=get_metadata(name),
                process_revision_directives=process_revision_directives,
                **current_app.extensions['migrate'].configure_args
            )
            context.run_migrations(engine_name=name)

            if USE_TWOPHASE:
                rec['transaction'].prepare()

            rec['transaction'].commit()
        except:
            rec['transaction'].rollback()
            raise
        finally:
            rec['connection'].close()
```

**Comment by miguelgrinberg** [comment]
This is something that needs to be discussed in the Alembic project, Flask-Migrate does not have anything to do with actual migration logic.
