### ISSUE TITLE
Possible bug in Alembic impacts init with `--multidb` flag causes failing `env.py`

### ISSUE THREAD

**Issue by thinkjrs** [miguelgrinberg/Flask-Migrate#314]
While freshly initializing two databases today I received:
```
AttributeError: 'URL' object has no attribute 'replace' 
```
The offending line was in `migrations/env.py` number 34 in the loop to set the url's:
```python
for name, url in current_app.config.get("SQLALCHEMY_BINDS").items():
    context.config.set_section_option(name, "sqlalchemy.url",url.replace(
        '%', '%%'))
```

And I quickly fixed the issue by forcing the `url` object to a string:
```python
for name, url in current_app.config.get("SQLALCHEMY_BINDS").items():
    context.config.set_section_option(name, "sqlalchemy.url", str(url).replace(
        '%', '%%'))
```

I am using the `sqlalchemy.engine.url.URL` object to construct urls which populate my Flask and Flask-SQLAlchemy configurations. From the sqlalchemy documentation:
> This object is suitable to be passed directly to a create_engine() call: [docs reference](https://docs.sqlalchemy.org/en/13/core/engines.html?highlight=engine%20url%20url#sqlalchemy.engine.url.URL).

If this problem is with Flask-Migrate, I'm more than happy to submit a PR and/or will do the same for upstream, please let me know. I'm not familiar enough with the libraries themselves to know where the offenders are but this seems like a fairly straightforward fix.

###### The actual error

`flask db init --multidb` runs fine. Then I execute `flask db migrate` and receive:
```
Traceback (most recent call last):
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/flask_migrate/cli.py", line 90, in migrate
    rev_id, x_arg)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/flask_migrate/__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/alembic/command.py", line 214, in revision
    script_directory.run_env()
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/jason/.local/share/virtualenvs/artist-platform-beta-FbQjYsPp/lib/python3.7/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 34, in <module>
    context.config.set_section_option(name, "sqlalchemy.url", url.replace(
AttributeError: 'URL' object has no attribute 'replace'
```

**Comment by miguelgrinberg** [comment]
Yes, your fix is safe to add to this project, so please go ahead and submit a PR for it. Thanks!

**Comment by thinkjrs** [comment]
> Yes, your fix is safe to add to this project, so please go ahead and submit a PR for it. Thanks!

@miguelgrinberg Thanks so much! I'll tackle over the coming days 🎸
