### ISSUE TITLE
Tutorial part 4 problem

### ISSUE THREAD

**Issue by jinks145** [miguelgrinberg/Flask-Migrate#322]
I am trying to make my own blog based on your tutorial and I seem to have ran into a roadblock.
I initialized the db as you said but, I can't get my migrations part working. 
When I use `flask db migrate -m "users table"`,  flask would give me this:
```
Traceback (most recent call last):
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask_migrate/cli.py", line 89, in migrate
    _migrate(directory, message, sql, head, splice, branch_label, version_path,
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask_migrate/__init__.py", line 210, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/alembic/command.py", line 214, in revision
    script_directory.run_env()
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 27, in <module>
    str(current_app.extensions['migrate'].db.engine.url).replace('%', '%%'))
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 937, in engine
    return self.get_engine()
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 947, in get_engine
    state = get_state(app)
  File "/home/brad/.virtualenvs/flaskdemo-5WCDTh0_/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 591, in get_state
    assert 'sqlalchemy' in app.extensions, \
AssertionError: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
```
What would cause this error?
My version of the blog:
https://github.com/jinks145/blog

**Comment by miguelgrinberg** [comment]
The error is clear:

```
AssertionError: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
```

You are not initializing the Flask-SQLAlchemy extension, which Flask-Migrate requires. Are you following my tutorial? This is very clearly covered there.

**Comment by jinks145** [comment]
nevermind, I forgot to initialize it.
