### ISSUE TITLE
Unable to do a flask db upgrade to create a new database

### ISSUE THREAD

**Issue by chrisbog** [miguelgrinberg/Flask-Migrate#325]
I am writing an application very similar to your mega tutorial.    My database is for keeping track of music recordings.   When I attempted to start with a fresh database, I ran:

`flask db upgrade`

When I attempted to do this, I get the following:   I'm not really sure but yes, I know the configuration table doesn't exist.   But I would have assumed the 'flask db upgrade' would build the database.

```
Home-iMac:musicdb chris$ flask db upgrade
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: configuration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 411, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 377, in load_app
    raise_if_not_found=False)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/chris/coding/musicdb/app/__init__.py", line 30, in <module>
    if musicdb_config.getitem("LOGGING") == 'DEBUG':
  File "/Users/chris/coding/musicdb/app/appconfig.py", line 13, in getitem
    results = qry.all()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2925, in all
    return list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3106, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: configuration [SQL: 'SELECT configuration."key" AS configuration_key, configuration.value AS configuration_value \nFROM configuration \nWHERE configuration."key" = ?'] [parameters: ('LOGGING',)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by miguelgrinberg** [comment]
You seem to be running database queries just by the fact your application instance is imported. There is a chicken and egg situation there. To upgrade (or create) the database you have to import the app, but to import the app you need to query the database.

You need to make importing the app be independent of having a usable database.

**Comment by chrisbog** [comment]
That makes sense I guess.

So in your mega tutorial, if you are storing configuration items in the database, where in your app would you access that stuff.

I initially used the __init__.py module, but maybe there is another place that would be better for initialization.

**Comment by miguelgrinberg** [comment]
My opinion is that it is a bad design choice to store configuration in the database. Certainly there should be a base set of configuration items that are not in the database. Any configuration items that are needed to initialize the app should not be in a database, or at least the app should be able to initialize if those settings aren't found.

**Comment by chrisbog** [comment]
Miguel.   Thank you.   You are probably correct about this one.   I refactored my application and removed the database queries outside of that module.
