### ISSUE TITLE
Sqlite: Adding new column to DB model breaks flask db migrate.

### ISSUE THREAD

**Issue by David00** [miguelgrinberg/Flask-Migrate#345]
I am building a Flask project and referencing the mega tutorial you've published, which, by the way, is fantastic, so thank you for that!

Anyways, as my project matures, I've had the need to modify my **already initialized** SQLite db.  My project structure mirrors the Microblog so far - my SQLite table definitions are in `models.py`.  I've already created the table and added a few items to it, but now I need to add another column. I updated my class definition in `models.py` with the following addition:  `is_active = db.Column(db.BOOLEAN, index=True)`

Here is the full class definition:

```
class Pilot(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    is_active = db.Column(db.BOOLEAN, index=True)
    flights = db.relationship('Flight', backref='pilot', foreign_keys='Flight.pilot_id')

    def __repr__(self):
            return f"<Pilot> {self.username}"

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
```

After saving the file, I run `flask db migrate` in my virtual environment, and I get two tracebacks. 

The first comes from Sqlite:

```
(venv) $ flask db migrate
Traceback (most recent call last):
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: pilot.is_active
```

The second exception comes from Sqlalchemy (this is a direct continuation of the traceback from above):

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aero/python-projects/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/aero/python-projects/main.py", line 1, in <module>
    from app import app, db
  File "/home/aero/python-projects/app/__init__.py", line 18, in <module>
    from app import routes, models
  File "/home/aero/python-projects/app/routes.py", line 4, in <module>
    from app.forms import LoginForm, AddFlightForm
  File "/home/aero/python-projects/app/forms.py", line 20, in <module>
    class AddFlightForm(FlaskForm):
  File "/home/aero/python-projects/app/forms.py", line 27, in AddFlightForm
    copilot_list = SelectField("Select a copilot", coerce=int, default = ("", ""), choices = get_pilots(), validators=[])
  File "/home/aero/python-projects/app/models.py", line 63, in get_pilots
    allPilots = Pilot.query.all()
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3319, in all
    return list(self)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1323, in _execute_context
    self._handle_dbapi_exception(
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
    util.raise_(
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/aero/python-projects/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: pilot.is_active
[SQL: SELECT pilot.id AS pilot_id, pilot.username AS pilot_username, pilot.email AS pilot_email, pilot.password_hash AS pilot_password_hash, pilot.is_active AS pilot_is_active 
FROM pilot]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

I don't understand why sqlite and sqlalchemy are both complaining about a missing column. Isn't flask-migrate supposed to recognize that the column is new, and create the migration script to add it?  What am I missing?

I'm running Python 3.8.0 with the following flask/sql libraries:

```
(venv) $ pip freeze | grep -iE "sql|flask"
Flask==1.1.2
Flask-Bootstrap==3.3.7.1
Flask-Login==0.5.0
Flask-Migrate==2.5.3
Flask-SQLAlchemy==2.4.3
Flask-WTF==0.14.3
SQLAlchemy==1.3.17
WTForms-SQLAlchemy==0.1
```

Thank you!

**Comment by miguelgrinberg** [comment]
This is because you are running a db query in the global scope of your application. The query runs before the migration is generated, using the model with the new column added. It is not a good idea to have database queries running in the global scope, as you have no control over when they run. Move that query to a function that you call to initialize your form to avoid this problem.

**Comment by David00** [comment]
Thanks Miguel. I took a look through my code again and could not find any global queries. 

I have only three queries total right now, and all of them are inside functions. Here are the three queries and their function definitions:

```
$ grep -B 10 -i "query" ./*.py --line-number | grep -Ei "query|def"

./models.py-58-def load_user(id):
./models.py:59:    return Pilot.query.get(int(id))
./models.py-62-def get_pilots():
./models.py:63:    allPilots = Pilot.query.all()
./routes.py-16-def login():
./routes.py:22:        user = Pilot.query.filter_by(username=form.username.data).first()
```

I wasn't sure how executing a query in a return statement would be treated by flask migrate (line 59 above), so  I moved the query more into the body of the function and returned an integer. Same traceback when calling `flask db migrate`.

**Comment by David00** [comment]
I found it - the query was inside of my form class definition where I dynamically populate the available selections in a `SelectField`.  The `get_pilots()` function is the query.

```
class AddFlightForm(FlaskForm):
    # ... other fields removed for brevity ... 
    copilot_list = SelectField("Select a copilot", coerce=int, default = ("", ""), choices = get_pilots(), validators=[])
```

For anyone reading this in the future, the solution is to populate the `choices` after you instantiate the form in the route. Example:

```
def add_flight():
    form = AddFlightForm()
    form.copilot_list.add_choices(get_pilots())
```

Thanks Miguel!!
