### ISSUE TITLE
How to use migrate with gunicorn+flask+MySQL

### ISSUE THREAD

**Issue by gaoyadianta** [miguelgrinberg/Flask-Migrate#356]
I have a proj using flask+gunicorn+MySQL, and the directory is like this:
```
├── Pipfile
├── Pipfile.lock
├── README.md
├── __init__.py
├── app
│   ├── __init__.py
│   ├── login.py
│   ├── system.py
│   ├── model.py
│   ├── task.py
│   └── view.py
├── config.py
├── gunicorn.conf
├── requirements.txt
├── tests
│   └── testurl.py
└── wsgi.py
```

There is a function factory in app/__init__.py, like this:
```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

def create_app(conf):

    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = DATA_BASE_PATH
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app=app)
    with app.app_context():
        db.create_all()

    app.register_blueprint(blueprint=view, url_prefix='/view/')

    socketio.init_app(app, async_mode=None)
    login_init(app)

    return app


```
and in the file wsgi.py, i have:
```python
from app import create_app
from config import app_conf
from app import socketio

app = create_app(app_conf)

if __name__ == "__main__":
    socketio.run(app=app, host=host, use_reloader=False)
    
```

If i want to run this porj, i use:
```shell
gunicorn -c gunicorn.conf wsgi:app
```

now i want to use flask-migrate to update the MySQL table change automaticly, but i am wondering where shoud i init the migrate and run my app? i have tried do that in wsgi.py or in app/__init__.py, but neither works...
please give me a hand, thanks ahead.

**Comment by miguelgrinberg** [comment]
What do you mean by "neither works"? I can't really comment on the problem without exact details.

**Comment by gaoyadianta** [comment]
> What do you mean by "neither works"? I can't really comment on the problem without exact details.

i have tried like this in app/__init__.py:
```python
from flask_migrate import Migrate
migrate = Migrate()

def create_app() 
    migrate.init_app(app)  
    # your original code here
```
and then run 
```shell
flask db init
```
that says:
```shell
* Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them. Usage: flask db migrate [OPTIONS] Error: While importing "application.app", an ImportError was raised: Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app import__(module_name) File "/Users/lbj/work/gitlab/far/application/app/__init.py", line 9, in <module> from app.task import task ModuleNotFoundError: No module named 'app'
```

**Comment by miguelgrinberg** [comment]
First of all the migrate extension takes two arguments, app and db:

    migrate.init_app(app, db)

Second, you have a `create_all()` call in there. If you are going to use Flask-Migrate to manage your db schema then create_all needs to be removed, since it competes with it.

Try these changes and let me know if there are still errors.

**Comment by gaoyadianta** [comment]
> First of all the migrate extension takes two arguments, app and db:
> 
> ```
> migrate.init_app(app, db)
> ```
> 
> Second, you have a `create_all()` call in there. If you are going to use Flask-Migrate to manage your db schema then create_all needs to be removed, since it competes with it.
> 
> Try these changes and let me know if there are still errors.

Thans for your reply! I have tried like you sadi, the app/__init__.py is like this:
```python
from flask_migrate import Migrate

migrate = Migrate()

def create_app(conf):

    pymysql.install_as_MySQLdb()
    DATA_BASE_PATH = 'mysql://root:chuangxin@127.0.0.1:3306/jms_backend'

    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = DATA_BASE_PATH
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app=app)
    migrate.init_app(app, db)  
    CORS(app, supports_credentials=True, origins=['http://localhost:3000', 'http://192.168.*.*:3000'])

    app.config.from_object(conf)
    app.json_encoder = JSONEncoder

    app.register_blueprint(blueprint=task, url_prefix='/task/')
    app.register_blueprint(blueprint=view, url_prefix='/view/')
  
    socketio.init_app(app, async_mode=None)

    login_init(app)

    return app
```

but, when i ran `flask db init`, it truned out the same error:
```shell
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: flask db init [OPTIONS]

Error: While importing "application.app", an ImportError was raised:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/lbj/work/gitlab/far/application/app/__init__.py", line 9, in <module>
    from app.task import task
ModuleNotFoundError: No module named 'app'
```

**Comment by miguelgrinberg** [comment]
I honestly don't see how adding Flask-Migrate to your project can cause this error. Are you able to run any other `flask` commands at all? This seems more like a misconfiguration of your Flask app, or maybe an incorrectly set `PYTHONPATH`.

**Comment by gaoyadianta** [comment]
> I honestly don't see how adding Flask-Migrate to your project can cause this error. Are you able to run any other `flask` commands at all? This seems more like a misconfiguration of your Flask app, or maybe an incorrectly set `PYTHONPATH`.

OK, i will have a try.
Will let you konw the result

**Comment by gaoyadianta** [comment]
> I honestly don't see how adding Flask-Migrate to your project can cause this error. Are you able to run any other `flask` commands at all? This seems more like a misconfiguration of your Flask app, or maybe an incorrectly set `PYTHONPATH`.

I think you are right. I can run any flask cli command.
but i have tried
```shell
export FLASK_APP=app
```
and
```shell
export FLASK_APP=application.app
```
and
```shell
export FLASK_APP=wsgi
```
and also tried run flask run with blank FLASK_APP. But none of them worked.
almost the same error about import module 'app', like:
```shell
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app ""
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "application.wsgi", an ImportError was raised:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/lbj/work/gitlab/far/application/wsgi.py", line 1, in <module>
    from app import create_app
ModuleNotFoundError: No module named 'app'
```
can you please give me some suggestion on how to set FLASK_APP? Thank you

**Comment by miguelgrinberg** [comment]
Did you try `FLASK_APP=wsgi.py`?

**Comment by gaoyadianta** [comment]
> Did you try `FLASK_APP=wsgi.py`?

Tried that just now, error:
```shell
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app "wsgi.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "application.wsgi", an ImportError was raised:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/lbj/work/gitlab/far/application/wsgi.py", line 1, in <module>
    from app import create_app
ModuleNotFoundError: No module named 'app'
```

**Comment by miguelgrinberg** [comment]
Run `flask run` from the directory where `wsgi.py` is located. It seems you are doing it from one directory above it.

**Comment by gaoyadianta** [comment]
> Run `flask run` from the directory where `wsgi.py` is located. It seems you are doing it from one directory above it.

I have tried both of them,
when from the directory where `wsgi.py` is located, output is shown in my last reply.
when from the directory above  `wsgi.py` is located, output is:
```shell
 * Serving Flask app "wsgi.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "wsgi".
```

**Comment by miguelgrinberg** [comment]
When you are in the directory where wsgi.py is located, do you also have a `__init__.py` in there? Try removing it or renaming it.

**Comment by gaoyadianta** [comment]
> When you are in the directory where wsgi.py is located, do you also have a `__init__.py` in there? Try removing it or renaming it.

Yes, there is a blank file `__init__.py` in the directory where wsgi.py is located.

I don't know why but `python3 -m flask ...` worked finally. If i ran `python3 -m flask run`, my app seems work fine.

However, new error came when i ran `python3 -m flask db init`:
```shell
[2020-07-10 18:28:44,963] WARNING in __init__: Flask-SocketIO is Running under Werkzeug, WebSocket is not available.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_migrate/cli.py", line 31, in init
    _init(directory, multidb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_migrate/__init__.py", line 126, in init
    directory = current_app.extensions['migrate'].directory
KeyError: 'migrate'
```

**Comment by miguelgrinberg** [comment]
@gaoyadianta Okay, we're making progress. This last error occurs because you haven't initialized the Flask-Migrate extension. This is a normal Flask extension that needs to be initialized along the others that you have. See the [docs](https://flask-migrate.readthedocs.io/en/latest/#example).

**Comment by gaoyadianta** [comment]
> @gaoyadianta Okay, we're making progress. This last error occurs because you haven't initialized the Flask-Migrate extension. This is a normal Flask extension that needs to be initialized along the others that you have. See the [docs](https://flask-migrate.readthedocs.io/en/latest/#example).

It worked finally, thanks
