### ISSUE TITLE
Not able to install with ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by shinokada** [miguelgrinberg/Flask-Migrate#360]
I'm getting errors as follows.

I use Python 3.8.2 with pyenv, wheel version is 0.35.1.
How can I fix it?

```
❯ pip install Flask-Migrate
Collecting Flask-Migrate
  Using cached Flask_Migrate-2.5.3-py2.py3-none-any.whl (13 kB)
Collecting alembic>=0.7
  Using cached alembic-1.4.2.tar.gz (1.1 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/shinokada/.pyenv/versions/3.8.2/envs/py382/bin/python3.8 /Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/17/2xhf1tw15xzd8sz_0hw3gp2h0000gn/T/pip-build-env-88phoxk8/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (31 lines):
  Traceback (most recent call last):
    File "/Users/shinokada/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Users/shinokada/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Users/shinokada/.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 22, in <module>
      from pip._internal.req.constructors import (
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 10, in <module>
      from .req_install import InstallRequirement
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 10, in <module>
      import uuid
    File "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/uuid.py", line 138
      if not 0 <= time_low < 1<<32L:
                                  ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/shinokada/.pyenv/versions/3.8.2/envs/py382/bin/python3.8 /Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/17/2xhf1tw15xzd8sz_0hw3gp2h0000gn/T/pip-build-env-88phoxk8/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by miguelgrinberg** [comment]
You seem to have a package called `uuid` that is for Python 2 installed in your virtual environment. Try uninstalling it.

**Comment by shinokada** [comment]
Thanks. 
It works now.
