### ISSUE TITLE
KeyError: 'migrate' on heroku

### ISSUE THREAD

**Issue by Emmanuel-Temitope** [miguelgrinberg/Flask-Migrate#370]
when I try to run `heroku flask db migrate ` or `heroku flask db upgrade ` on Heroku.
Heroku gives me the error  below:

Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_migrate/__init__.py", line 269, in upgrade
    config = current_app.extensions['migrate'].migrate.get_config(directory,
KeyError: 'migrate'

**Comment by miguelgrinberg** [comment]
I assume you mean `heroku run flask db ...`? Or are you just saying `heroku flask db ...`?

In any case, the error has nothing to do with Heroku, the problem is that your Flask-Migrate extension is not configured in your Flask application instance.

**Comment by Emmanuel-Temitope** [comment]
yes

**Comment by Emmanuel-Temitope** [comment]
sorry, `heroku run flask db upgrade` or `heroku run flask db migrate`
but if I run it from the Procfile:` heroku run migrate` or `heroku run upgrade`
`web: gunicorn app:app`
`init: python manage.py db init`
`migrate: python manage.py db migrate`
`upgrade: python manage.py db upgrade`

it gives me the error:
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    manager.run()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_migrate/__init__.py", line 212, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/command.py", line 214, in revision
    script_directory.run_env()
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 96, in <module>
    run_migrations_online()
  File "migrations/env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/runtime/migration.py", line 511, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/command.py", line 190, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 442, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 454, in _run_environment
    self.script_directory.get_revisions("heads")
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/script/base.py", line 227, in get_revisions
    return self.revision_map.get_revisions(id_)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/script/revision.py", line 321, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/script/revision.py", line 501, in _resolve_revision_number
    self._revision_map
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/util/langhelpers.py", line 230, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/script/revision.py", line 123, in _revision_map
    for revision in self._generator():
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/script/base.py", line 103, in _load_revisions
    for file_ in Script._list_py_dir(self, vers):
  File "/app/.heroku/python/lib/python3.6/site-packages/alembic/script/base.py", line 876, in _list_py_dir
    return os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/app/migrations/versions'

**Comment by miguelgrinberg** [comment]
Still, these problems are based app set up problems, they have nothing to do with Heroku. This second error occurs because you don't have your migrations directory does not exist in Heroku. If you are using git to deploy to Heroku, then you likely did not add the migrations directory to source control.

**Comment by Emmanuel-Temitope** [comment]
Well, I configured it.
In my app.py file :

`migrate = Migrate(app, db)`

**Comment by Emmanuel-Temitope** [comment]
Well, I added the migrations folder. I didn't add it to the .gitignore file

**Comment by Emmanuel-Temitope** [comment]
Well, do you mind if I invite you to the git repo to check it out.

**Comment by miguelgrinberg** [comment]
Sorry, I don't have time. I'm telling you what the issues are just by simply reading your stack traces. If the stack trace says `No such file or directory: '/app/migrations/versions'` and you tell me you have your migrations folder in the repo I have to believe the stack trace. You need to debug this to figure out why the files that you think are in the repo aren't.

**Comment by Emmanuel-Temitope** [comment]
@miguelgrinberg I have re-created the app and have committed every file to heroku, 
but it's still the same. In the git repo, the files are all present but it's still the same error.
Please, I have been trying to debug this issue since yesterday but still the same error.

**Comment by Emmanuel-Temitope** [comment]
@miguelgrinberg my app is not a package, I just simply use app.py for the app.
Do you think that's where the problem originates from, my file structure?

**Comment by miguelgrinberg** [comment]
You are not providing accurate details. You say that you get "the same error", but you have described two completely unrelated error situations in this issue.

A single app.py is a valid file structure for Flask.

**Comment by Emmanuel-Temitope** [comment]
> You are not providing accurate details. You say that you get "the same error", but you have described two completely unrelated error situations in this issue.
> 
> A single app.py is a valid file structure for Flask.

@miguelgrinberg ok, sir.

**Comment by Emmanuel-Temitope** [comment]
@miguelgrinberg if so sir, from my application structure the migrations folder is not in a directory named `app/migrations`
it's just `migrations`
![Annotation 2020-10-29 211648](https://user-images.githubusercontent.com/43725109/97627816-32513c80-1a2c-11eb-8bde-136461fa2d2f.jpg)

**Comment by miguelgrinberg** [comment]
Heroku installs your application in the `/app` folder, if I remember correctly.

**Comment by Emmanuel-Temitope** [comment]
> Heroku installs your application in the `/app` folder, if I remember correctly.

Yes, you are correct sir. whenever I run `heroku run init` i.e `init: python manage.py db` init, it detects the migrations folder.
![Annotation 2020-10-30 020620](https://user-images.githubusercontent.com/43725109/97648248-8c65f800-1a54-11eb-9d65-43145a0f4252.jpg)
but if I run `heroku run migrate` it gives me this:
![Uploading Annotation 2020-10-30 020920.jpg…]()

**Comment by miguelgrinberg** [comment]
And did you notice the two errors are about different folders? The first is for `/app/migrations`, while the second is about `/app/migrations/versions`.

Secondary to that, you shouldn't be calling `flask db migrate` on Heroku, there is no point in doing that and the tutorial never asks you to do it.

**Comment by Emmanuel-Temitope** [comment]
> And did you notice the two errors are about different folders? The first is for `/app/migrations`, while the second is about `/app/migrations/versions`.
> 
> Secondary to that, you shouldn't be calling `flask db migrate` on Heroku, there is no point in doing that and the tutorial never asks you to do it.

Yes, flask db migrate is not in the tutorial.

**Comment by Emmanuel-Temitope** [comment]
@miguelgrinberg but when I run `heroku run upgrade` it gives me this:
![Annotation 2020-10-30 221612](https://user-images.githubusercontent.com/43725109/97757714-91cb4d00-1afd-11eb-86fc-4dcd362319cb.jpg)

**Comment by miguelgrinberg** [comment]
The `versions` subdirectory is inside the `migrations` directory and needs to be included in your repository.

**Comment by Emmanuel-Temitope** [comment]
@miguelgrinberg Thanks you. That was the issue
