### ISSUE TITLE
flask db init fails PermissionError: [Errno 1] Operation not permitted: 'migrations/script.py.mako'

### ISSUE THREAD

**Issue by emilh18** [miguelgrinberg/Flask-Migrate#389]
Hi Miguel!

I'm attempting to use your flask-migrate CLI tool as per your [tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database).

Issue:
after flask db init

PermissionError: [Errno 1] Operation not permitted: 'migrations/script.py.mako'

Context:

I use WSL. I've exported FLASK_APP='run.py', where run.py does the import of 'app' and 'db' from (myapp)/__init__.py	

I tried also sudo flask db init, but that does not work either.

Can you please point me in the right direction?

Thanks a lot in advance

**Comment by miguelgrinberg** [comment]
Please provide the complete error message.

**Comment by emilh18** [comment]
Creating directory /mnt/c/Users/haase/Documents/VL/recruit_app/migrations ...  done
  Creating directory /mnt/c/Users/haase/Documents/VL/recruit_app/migrations/versions ...  done
  Generating /mnt/c/Users/haase/Documents/VL/recruit_app/migrations/script.py.mako ...  FAILED
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/emil/.local/lib/python3.8/site-packages/flask_migrate/cli.py", line 32, in init
    _init(directory, multidb)
  File "/home/emil/.local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/home/emil/.local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 135, in init
    command.init(config, directory, 'flask')
  File "/home/emil/.local/lib/python3.8/site-packages/alembic/command.py", line 83, in init
    script._copy_file(file_path, output_file)
  File "/home/emil/.local/lib/python3.8/site-packages/alembic/script/base.py", line 507, in _copy_file
    util.status(
  File "/home/emil/.local/lib/python3.8/site-packages/alembic/util/messaging.py", line 50, in status
    ret = fn(*arg, **kw)
  File "/usr/lib/python3.8/shutil.py", line 416, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 305, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: 'migrations/script.py.mako'

**Comment by miguelgrinberg** [comment]
This is probably a permissions issue. Check all the directories and files in your project and make sure they are writable by your user.

**Comment by emilh18** [comment]
hm, as I am new to WSL and Linux  I tried this approach for checking that https://unix.stackexchange.com/questions/19002/determine-if-the-current-user-has-write-permission-in-a-directory

And it seems the directories are writable by current user.

Actually by the flask db init command a new folder called migrations with a subfolder + one file was created, what suggest to me  that the directory should be writable to make this happen or that is wrong deduction?

Do you have any other idea or can the checking method from the link be invalid?

thank you for your answer

**Comment by miguelgrinberg** [comment]
It seems this is a specific issue with WSL, where the chmod command isn't enabled by default. See https://stackoverflow.com/questions/46610256/chmod-wsl-bash-doesnt-work.

**Comment by emilh18** [comment]
yes, this helped. Thank you very much Miguel!
