### ISSUE TITLE
Unable to upgrade database model after IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed

### ISSUE THREAD

**Issue by emilh18** [miguelgrinberg/Flask-Migrate#390]
Hi Miguel,
When I was using query on my database with flask-sqlalchemy I got an error:

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: candidate.name
[SQL: INSERT INTO candidate (name, owner, contact_date, contact_year, contact_quarter, contact_month, status, position, final_result, country, seniority, exp_seniority, source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Viktor Lacina', 'Beata Bilická', '2020-10-28', '2020', '2020/12-10', '2020/10', 'Invitation', "['developer']", '', 'CZ', '', '', 'Bea')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

I realized that probably some name in the data was duplicate, so I change the name column in the Candidate class to     
name = db.Column(db.String(64), index=False, unique=False)
and wanted to apply the change, so ran "flask db migrate" afterwards. But unfortunately got the same error again:

$ flask db migrate
Traceback (most recent call last):
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: candidate.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/mnt/c/Users/haase/Documents/VL/recruit_app/run.py", line 1, in <module>
    from web import app, db
  File "/mnt/c/Users/haase/Documents/VL/recruit_app/web/__init__.py", line 29, in <module>
    from web import routes, models
  File "/mnt/c/Users/haase/Documents/VL/recruit_app/web/routes.py", line 5, in <module>
    from recruit_app import data
  File "/mnt/c/Users/haase/Documents/VL/recruit_app/recruit_app.py", line 9, in <module>
    download_candidates(2000)
  File "/mnt/c/Users/haase/Documents/VL/recruit_app/download_data.py", line 81, in download_candidates
    db.session.commit()
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/emil/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: candidate.name
[SQL: INSERT INTO candidate (name, owner, contact_date, contact_year, contact_quarter, contact_month, status, position, final_result, country, seniority, exp_seniority, source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Viktor Lacina', 'Beata Bilická', '2020-10-28', '2020', '2020/12-10', '2020/10', 'Invitation', "['developer']", '', 'CZ', '', '', 'Bea')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

Is there any other way to fix corrupted database?

Thanks a lot in advance

**Comment by miguelgrinberg** [comment]
You appear to have database code that runs automatically when your application is imported, without calling any functions. The stack trace points to a `download_candidates()` function. That is not a good idea, because it causes database calls when Alembic is importing the app to generate a migration. Try removing that and see if that helps.

**Comment by emilh18** [comment]
Thank you, that was really the problem. I cancelled the dependencies and now it works.

**Comment by Franklinson** [comment]
I had same issue but when I ran the flask db migrate it says "INFO  [alembic.env] No changes in schema detected." Any help please
