### ISSUE TITLE
Not sure if this is a Flask-Migrate problem, a SQLAlchemy problem, or an Alembic problem, but when I replace your example code with a postgres url, it doesn't work and produces this error.

### ISSUE THREAD

**Issue by deino475** [miguelgrinberg/Flask-Migrate#391]
c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_sqlalchemy\__init__.py:833: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(
Traceback (most recent call last):
  File "C:\Users\Nile Dixon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Nile Dixon\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nile Dixon\Desktop\TestFlask\env\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_migrate\cli.py", line 91, in migrate
    _migrate(directory, message, sql, head, splice, branch_label, version_path,
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_migrate\__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_migrate\__init__.py", line 210, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\alembic\command.py", line 212, in revision
    script_directory.run_env()
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\alembic\util\compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 25, in <module>
    str(current_app.extensions['migrate'].db.engine.url).replace('%', '%%'))
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 943, in engine
    return self.get_engine()
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 556, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 972, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\sqlalchemy\engine\create.py", line 520, in create_engine
    entrypoint = u._get_entrypoint()
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\sqlalchemy\engine\url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "c:\users\nile dixon\desktop\testflask\env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 341, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

**Comment by miguelgrinberg** [comment]
What's the URL that you are using?

**Comment by deino475** [comment]
postgres://postgres:password@localhost:5432/niletest

**Comment by miguelgrinberg** [comment]
That's an invalid SQLAlchemy URL. Find the Postgres driver that you are using in [this page](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.base) to find out what the correct URL is.

**Comment by deino475** [comment]
I am confused. I have used this URL formatting in previous flask projects with Flask Migrate and Flask SQLAlchemy and it worked.

**Comment by miguelgrinberg** [comment]
Sorry, but a description of what you did is not sufficient. What URL did you use now?

**Comment by deino475** [comment]
postgres+psycopg2://postgres:password@localhost:5432/niletest

When I go into the project directory with my virtual environment and type "flask db migrate", I receive the error above. 

Here is a link to the repo: https://github.com/deino475/Test-Flask-App

**Comment by miguelgrinberg** [comment]
Yes, and you are not reading the docs correctly. Try `postgresql+psycopg2://...`.

**Comment by deino475** [comment]
Lol, what the heck. I am looking at older projects that I've coded and simply using "postgres" instead of "postgresql" has worked on older version of Alembic, SQLAlchemy, and Flask Migrate. 

😭 Sorry for wasting your time.
