### ISSUE TITLE
inspect_getfullargspec cannot not import.

### ISSUE THREAD

**Issue by karthikeyanrathore** [miguelgrinberg/Flask-Migrate#440]
```
flask db
Traceback (most recent call last):
  File "/usr/bin/flask", line 11, in <module>
    load_entry_point('Flask==0.12.2', 'console_scripts', 'flask')()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 336, in get_command
    self._load_plugin_commands()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 332, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 7, in <module>
    from alembic import __version__ as __alembic_version__
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 12, in <module>
    from .migration import MigrationContext
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 27, in <module>
    from .. import ddl
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/ddl/mssql.py", line 14, in <module>
    from .base import AddColumn
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/ddl/base.py", line 14, in <module>
    from ..util.sqla_compat import _columns_for_constraint  # noqa
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/util/__init__.py", line 1, in <module>
    from .editor import open_in_editor
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/util/editor.py", line 11, in <module>
    from .compat import is_posix
  File "/home/karthikeyan/.local/lib/python3.6/site-packages/alembic/util/compat.py", line 5, in <module>
    from sqlalchemy.util import inspect_getfullargspec  # noqa
ImportError: cannot import name 'inspect_getfullargspec'

```

**Comment by miguelgrinberg** [comment]
This isn't related to Flask-Migrate, you have an incompatibility between SQLAlchemy and Alembic. Try upgrading both to their latest versions.
