### ISSUE TITLE
Droping a constrain  with name None leads to fail to upgrade

### ISSUE THREAD

**Issue by Zaker237** [miguelgrinberg/Flask-Migrate#445]
hi i reccently update my model by adding a new foreign key to a specific table and my table looks like

```python
class File(db.Model):
    __tablename__ = "file"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80))
    description = db.Column(db.Text)
    is_binary = db.Column(db.Boolean, default=False)
    path = db.Column(db.String(255), unique=True, nullable=False)
    model_id = db.Column(db.Integer, db.ForeignKey("model.id"), nullable=False)
```

i genared the migration fille wtith flask db migrate and get the following

```python
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'model', ['model_id'], ['id'])

    with op.batch_alter_table('role_group_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])

    with op.batch_alter_table('role_user_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_user_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['user_id'], ['id'])

    with op.batch_alter_table('role_group_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['group_id'], ['id'])

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model_id')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
```

but when i run the upgrade i get the following error 

```console
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 92cc8c32e15f -> 756329c8f28d, add model_id in file
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/cli.py", line 149, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 91, in <module>
    run_migrations_online()
  File "migrations/env.py", line 85, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "/code/migrations/versions/756329c8f28d_add_model_id_in_file.py", line 24, in upgrade
    batch_op.create_foreign_key(None, 'model', ['model_id'], ['id'])
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/base.py", line 374, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/batch.py", line 138, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/operations/batch.py", line 625, in add_constraint
    raise ValueError("Constraint must have a name")
ValueError: Constraint must have a name
```

i dont really understant what is going on. i did get such an error in the pass. 

i also try the alternati with name from [here](https://programmerwiki.com/article/99571056289/)

this time i get a Out of the range error that i was not able to fing the origin.

Please can someone help me figure out this error??

**Comment by miguelgrinberg** [comment]
Your question relates to Alembic and not to Flask-Migrate. There is documentation on constraint names here: https://alembic.sqlalchemy.org/en/latest/naming.html.

**Comment by kipkosgeii** [comment]
1. ALTER tables is not supported by SQLite3. 
     On your database instance where you created a Migrate initialization change env

       ~  migrate = Migrate(app,db)
sol:
       ~  migrate=Migrate(app,db, render_as_batch=True)

or if you passed as a function add the same "render_as_batch=True"
