### ISSUE TITLE
new alembic version is 0.7.5.post1 breaks

### ISSUE THREAD

**Issue by XenGi** [miguelgrinberg/Flask-Migrate#54]
With the new alembic version Flask-Migrate can't figure out what version alembic has.

```
$ ./manage.py 
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from endor import MANAGER
  File "/home/ffwi/endor/endor/__init__.py", line 16, in <module>
    from flask.ext.migrate import Migrate, MigrateCommand
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/ffwi/endor/venv/lib/python3.4/site-packages/flask/exthook.py", line 62, in load_module
    __import__(realname)
  File "/home/ffwi/endor/venv/lib/python3.4/site-packages/flask_migrate/__init__.py", line 9, in <module>
    alembic_version = tuple([int(v) for v in __alembic_version__.split('.')])
  File "/home/ffwi/endor/venv/lib/python3.4/site-packages/flask_migrate/__init__.py", line 9, in <listcomp>
    alembic_version = tuple([int(v) for v in __alembic_version__.split('.')])
ValueError: invalid literal for int() with base 10: 'post1'
```

**Comment by XenGi** [comment]
duplicate of #53
