### ISSUE TITLE
support alembic version strings

### ISSUE THREAD

**Issue by spikergit1** [miguelgrinberg/Flask-Migrate#57]
When running a migrate command:

```
Traceback (most recent call last):
  File "/home/vagrant/EngScripts/resourceman/trunk/venv/bin/xes_rm-manager", line 9, in <module>
    load_entry_point('xes-rm==1.2115', 'console_scripts', 'xes_rm-manager')()
  File "/home/vagrant/EngScripts/resourceman/trunk/src/xes_rm/app.py", line 63, in manager
    from flask.ext.migrate import Migrate, MigrateCommand
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/vagrant/EngScripts/resourceman/trunk/venv/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/exthook.py", line 62, in load_module
    __import__(realname)
  File "/home/vagrant/EngScripts/resourceman/trunk/venv/lib/python3.4/site-packages/Flask_Migrate-1.3.0-py3.4.egg/flask_migrate/__init__.py", line 9, in <module>
    alembic_version = tuple([int(v) for v in __alembic_version__.split('.')])
  File "/home/vagrant/EngScripts/resourceman/trunk/venv/lib/python3.4/site-packages/Flask_Migrate-1.3.0-py3.4.egg/flask_migrate/__init__.py", line 9, in <listcomp>
    alembic_version = tuple([int(v) for v in __alembic_version__.split('.')])
ValueError: invalid literal for int() with base 10: 'post2'
```

**Comment by miguelgrinberg** [comment]
Have you upgraded Flask-Migrate to the latest release?

**Comment by spikergit1** [comment]
Yes, as in the log output:

`Flask_Migrate-1.3.0-py3.4.egg`

The issue is here: https://github.com/miguelgrinberg/Flask-Migrate/blob/master/flask_migrate/__init__.py#L9

The newest alembic version includes non-numeric characters.

**Comment by spikergit1** [comment]
Nevermind, apparently im one version behind.  Sorry for bothering.
