### ISSUE TITLE
How do I  add  "import  sqlalchemy_utils" automaitically to the migration file

### ISSUE THREAD

**Issue by Leo-G** [miguelgrinberg/Flask-Migrate#62]
I am using TSVectorType() to create tsvector column, but to upgrade the migration I need to add import  sqlalchemy_utils to migration file, How can I do this automatically?

**Comment by miguelgrinberg** [comment]
I'm not sure there is a way, since Alembic has no way to know how to import a third party column type.

**Comment by minhoryang** [comment]
I got a same issue when I tried to use sqlalchemy_utils without --multi-db.
http://stackoverflow.com/questions/30132370/trouble-when-using-alembic-with-sqlalchemy-utils
I won't upload the stacktrace because same stacktrace was printed.

I got a different issue when I tried to use with --multi-db.
```python_traceback
Traceback (most recent call last):
  File "manage.py", line 32, in <module>
    manager.run()
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_migrate/__init__.py", line 150, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "migrations/env.py", line 144, in <module>
    run_migrations_online()
  File "migrations/env.py", line 122, in run_migrations_online
    target_metadata=get_metadata(name)
  File "migrations/env.py", line 45, in get_metadata
    t.tometadata(m)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/sqlalchemy/sql/schema.py", line 823, in tometadata
    args.append(c.copy(schema=schema))
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/sqlalchemy/sql/schema.py", line 1324, in copy
    type_ = type_.copy(**kw)
TypeError: <flask_script.commands.Command object at 0x10e36d780>: copy() got an unexpected keyword argument 'schema'
```

My versions:
```
Flask==0.10.1
Flask-Admin==1.3.0
-e git+https://github.com/mattupstate/flask-jwt.git@51486d4d259f36234a3c73423e37cf4eb628a1d3#egg=Flask_JWT-origin/master
Flask-Migrate==1.5.0
Flask-RESTful==0.3.3
Flask-SQLAlchemy==2.0
Flask-Script==2.0.5
Jinja2==2.8
Mako==1.0.1
MarkupSafe==0.23
SQLAlchemy==1.0.8
SQLAlchemy-Enum34==1.0.1
SQLAlchemy-Utils==0.30.17
WTForms==2.0.2
Werkzeug==0.10.4
aiohttp==0.17.2
alembic==0.8.1
aniso8601==1.0.0
astroid==1.3.6
chardet==2.3.0
erequests==0.4.1
eventlet==0.17.4
flake8==2.4.1
flask-restplus==0.7.2
greenlet==0.4.7
gunicorn==19.3.0
itsdangerous==0.24
logilab-common==0.63.2
mccabe==0.3.1
newrelic==2.54.0.41
pep8==1.5.7
pyflake==0.1.9
pyflakes==0.9.2
pylint==1.4.3
python-editor==0.3
pytz==2015.4
requests==2.7.0
six==1.9.0
webargs==0.13.0
```

**Comment by imaia** [comment]
Maybe changing the default migration template?

**Comment by miguelgrinberg** [comment]
If you don't mind having the import in every migration, and not just on those that use those symbols, then sure, add them to the migration template.

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.

**Comment by techindustan** [comment]
Hi, I'm adding sqlalchemy_utils.types.uuid.UUIDType in models and the migration  is throwing `NameError: name 'sqlalchemy_utils' is not defined` after `flask db upgrade`. `flask db migrate` is running fine.
