### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_parser'

### ISSUE THREAD

**Issue by Avrong** [miguelgrinberg/Flask-Migrate#80]
Command:
```bash
./manage.py db migrate
```
Error:
```
Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    manager.run()
  File "/home/avrong/virtualenv/xnblog/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/avrong/virtualenv/xnblog/lib/python3.4/site-packages/flask_script/__init__.py", line 350, in handle
    app_parser = self.create_parser(prog)
  File "/home/avrong/virtualenv/xnblog/lib/python3.4/site-packages/flask_script/__init__.py", line 193, in create_parser
    command_parser = command.create_parser(name, func_stack=func_stack, parent=self)
AttributeError: 'NoneType' object has no attribute 'create_parser'
```
manage.py:
```python
from flask_script import Manager, Server
from flask_migrate import Migrate, MigrateCommand

from app import app
from app.models import *

migrate = Migrate(app, db)

manager = Manager(app)


def createall():
    db.create_all()

manager.add_command('runserver', Server)
manager.add_command('create', createall())
manager.add_command('db', MigrateCommand)


if __name__ == '__main__':
    manager.run()
```

**Comment by miguelgrinberg** [comment]
Can you post the output of `pip freeze` please?

**Comment by Avrong** [comment]
```
avrong@avrong-pc:~/virtualenv$ xnblog/bin/pip freeze
alembic==0.8.2
Flask==0.10.1
Flask-Login==0.2.11
Flask-Migrate==1.5.1
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-WTF==0.12
grab==0.6.23
itsdangerous==0.24
Jinja2==2.8
lxml==3.4.4
Mako==1.0.2
MarkupSafe==0.23
pycurl==7.19.5.1
python-editor==0.4
pytils==0.3
selection==0.0.11
six==1.9.0
SQLAlchemy==1.0.8
weblib==0.1.15
Werkzeug==0.10.4
WTForms==2.0.2
```
```
avrong@avrong-pc:~/PycharmProjects/XNBlog$ ./manage.py create
Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    manager.run()
  File "/home/avrong/virtualenv/xnblog/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/avrong/virtualenv/xnblog/lib/python3.4/site-packages/flask_script/__init__.py", line 350, in handle
    app_parser = self.create_parser(prog)
  File "/home/avrong/virtualenv/xnblog/lib/python3.4/site-packages/flask_script/__init__.py", line 193, in create_parser
    command_parser = command.create_parser(name, func_stack=func_stack, parent=self)
AttributeError: 'function' object has no attribute 'create_parser'
```
db file has been not created.

If...
```
manager.add_command('create', createall())
```
...there is that error, but db file has been created.
I think that problem with Flask-Script or in my code.

**Comment by miguelgrinberg** [comment]
You really do not need to create the database yourself, you can let Flask-Migrate do that for you.

Please remove the `create` command from your script.

**Comment by Avrong** [comment]
Thank you!

**Comment by Noble-mungu** [comment]
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    manager.run()
  File "D:\Downloads\Desktop\python-4\virtual\lib\site-packages\flask_script\__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "D:\Downloads\Desktop\python-4\virtual\lib\site-packages\flask_script\__init__.py", line 353, in handle
    app_parser = self.create_parser(prog)
  File "D:\Downloads\Desktop\python-4\virtual\lib\site-packages\flask_script\__init__.py", line 196, in create_parser
    command_parser = command.create_parser(name, func_stack=func_stack, parent=self)
AttributeError: 'function' object has no attribute 'create_parser'

**Comment by Noble-mungu** [comment]
I get this error when I want to run my server

**Comment by miguelgrinberg** [comment]
@Noble-mungu why are you using Flask-Script these days? I recommend you use the Flask CLI method.

**Comment by Noble-mungu** [comment]
I am running my application in production

**Comment by miguelgrinberg** [comment]
I'm not asking you to use `flask run`, just the Flask CLI to run your database migrations.
